actualizaciones varias, factorizacion, formateo

diff --git a/.config/nix-darwin/home/zsh_func b/.config/nix-darwin/home/zsh_func
--- a/.config/nix-darwin/home/zsh_func
+++ b/.config/nix-darwin/home/zsh_func
@@ -9,7 +9,7 @@ function brew() {
     fi
 }
 # function brew() {
-#   command brew "$@" 
+#   command brew "$@"
 #   if [[ $* =~ "upgrade" ]] || [[ $* =~ "update" ]] || [[ $* =~ "outdated" ]]; then
 #     sketchybar --trigger brew_update
 #   fi
@@ -53,12 +53,22 @@ function br {
     fi
 }
 
+function nug() {
+    export TERM=xterm-ghostty
+    if [[ -n "$GHOSTTY_RESOURCES_DIR" ]]; then
+        source "$GHOSTTY_RESOURCES_DIR/shell-integration/zsh/ghostty-integration"
+    fi
+    exec nu -l
+}
 
-#function suyabai () {
-#  SHA256=$(shasum -a 256 /opt/homebrew/bin/yabai | awk "{print \$1;}")
-#  if [ -f "/private/etc/sudoers.d/yabai" ]; then
-#    sudo sed -i '' -e 's/sha256:[[:alnum:]]*/sha256:'${SHA256}'/' /private/etc/sudoers.d/yabai
-#  else
-#    echo "sudoers file does not exist yet"
-#  fi
-#}
+# Función para correr just en nix-darwin desde cualquier lado
+function j() {
+  local dir="$HOME/.config/nix-darwin"
+  if [[ -d "$dir" ]]; then
+    cd "$dir" || { echo "Error: no se pudo entrar a $dir"; return 1; }
+    command just "$@"
+  else
+    echo "Error: no se encontró el directorio $dir"
+    return 1
+  fi
+}
